import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { HTTP_INTERCEPTORS, provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { JwtModule } from '@auth0/angular-jwt';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  AreaChart,
  BarChart3,
  Bookmark,
  Box,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  CircleDashed,
  Clock,
  Cloud,
  Cog,
  Copy,
  Cpu,
  Database,
  Download,
  Eye,
  EyeOff,
  Filter,
  FilterX,
  Gauge,
  Globe,
  Group,
  HardDrive,
  Hash,
  Info,
  Layers,
  LayoutGrid,
  Link,
  Loader2,
  LogOut,
  LucideAngularModule,
  Maximize2,
  MemoryStick,
  Minimize2,
  MoreVertical,
  Network,
  Package,
  Pause,
  Play,
  Plus,
  Power,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Server,
  Settings,
  Shield,
  Trash2,
  TrendingUp,
  User,
  Volume2,
  VolumeX,
  X,
  XCircle,
  ZoomIn,
  ZoomOut,
} from 'lucide-angular';
import {
  BarController,
  BarElement,
  CategoryScale,
  Colors,
  Filler,
  Legend,
  LineController,
  LineElement,
  LinearScale,
  PointElement,
} from 'chart.js';
import { provideCharts } from 'ng2-charts';
import { environment } from '../environments/environment';
import { JwtInterceptor } from './_services/jwt-interceptor';
import { routes } from './app.routes';

export function tokenGetter() {
  return localStorage.getItem('authToken');
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideHttpClient(withInterceptorsFromDi()),
    provideRouter(routes),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: JwtInterceptor,
      multi: true,
    },
    provideCharts({
      registerables: [
        BarController,
        LineController,
        Legend,
        Colors,
        CategoryScale,
        LinearScale,
        BarElement,
        LineElement,
        PointElement,
        Filler,
      ],
    }),
    importProvidersFrom(
      JwtModule.forRoot({
        config: {
          tokenGetter,
          allowedDomains: undefined,
          disallowedRoutes: [`${environment.apiUrl}/api/auth/login`],
        },
      })
    ),
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        AlertCircle,
        AlertTriangle,
        AreaChart,
        BarChart3,
        Bookmark,
        Box,
        Check,
        CheckCircle,
        ChevronDown,
        ChevronRight,
        CircleDashed,
        Clock,
        Cloud,
        Cog,
        Copy,
        Cpu,
        Database,
        Download,
        Eye,
        EyeOff,
        Filter,
        FilterX,
        Gauge,
        Globe,
        Group,
        HardDrive,
        Hash,
        Info,
        Layers,
        LayoutGrid,
        Link,
        Loader2,
        LogOut,
        Maximize2,
        MemoryStick,
        Minimize2,
        MoreVertical,
        Network,
        Package,
        Pause,
        Play,
        Plus,
        Power,
        RefreshCw,
        RotateCcw,
        Save,
        Search,
        Server,
        Settings,
        Shield,
        Trash2,
        TrendingUp,
        User,
        Volume2,
        VolumeX,
        X,
        XCircle,
        ZoomIn,
        ZoomOut,
      })
    ),
  ],
};
